const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const templateContent = require('./templateContent');

module.exports = (options) => [
  new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
  new webpack.NoErrorsPlugin(),
  new HtmlWebpackPlugin({
    inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
    templateContent: templateContent(options) // eslint-disable-line no-use-before-define
  })
];
